name: workflow

on:
  schedule:
    - cron:  "05 15 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: install dmm_search3
      run: pip3 install dmm_search3
      
    - name: run dmm_search3
      run: python3 test.py
      env:
        API_ID: ${{ secrets.API_ID }}
        AFFILIATE_ID: ${{ secrets.AFFILIATE_ID }}
